### ISSUE TITLE
ERROR: Service 'gpu-jupyter' failed to build: The command '/bin/bash -o pipefail -c jupyter labextension install @jupyterlab/github' returned a non-zero code: 1

### ISSUE THREAD

**Issue by dbabbitt** [iot-salzburg/gpu-jupyter#13]
This is what I ran in the "Git Bash Here" prompt on Windows 10:

```
$ cd gpu-jupyter
$ ./generate-Dockerfile.sh
$ bash start-local.sh -p 8889
```

This is what the output of `docker-compose logs -f` looks like:

```
$ docker-compose logs -f
ERROR: The Compose file '.\docker-compose.yml' is invalid because:
services.gpu-jupyter.ports contains an invalid type, it should be a number, or an object
```

**Comment by dbabbitt** [comment]
```
Building jupyterlab assets (build:prod:minimize)
An error occured.
RuntimeError: JupyterLab failed to build
See the log file for details:  /tmp/jupyterlab-debug-9jl9jf2i.log
ERROR: Service 'gpu-jupyter' failed to build: The command '/bin/bash -o pipefail -c jupyter labextension install @jupyterlab/github' returned a non-zero code: 1

Started gpu-jupyter via docker-compose on localhost:8889.
See docker-compose logs -f for logs.
```

The debug log looks like this:

```
# bash
root@5c8558e88e72:~# cat  /tmp/jupyterlab-debug-9jl9jf2i.log
Node v13.13.0

Yarn configuration loaded.
> /opt/conda/bin/npm pack @jupyterlab/github
npm notice
npm notice 📦  @jupyterlab/github@2.0.0
npm notice === Tarball Contents ===
npm notice 2.3kB  package.json
npm notice 1.5kB  LICENSE
npm notice 6.2kB  README.md
npm notice 2.3kB  lib/browser.d.ts
npm notice 13.0kB lib/browser.js
npm notice 6.5kB  lib/contents.d.ts
npm notice 23.0kB lib/contents.js
npm notice 4.8kB  lib/github.d.ts
npm notice 3.1kB  lib/github.js
npm notice 251B   lib/index.d.ts
npm notice 5.4kB  lib/index.js
npm notice 679B   schema/drive.json
npm notice 2.4kB  style/binder.svg
npm notice 2.7kB  style/index.css
npm notice 35.4kB style/octocat_error.png
npm notice 2.1kB  style/octocat-dark.svg
npm notice 2.1kB  style/octocat-light.svg
npm notice === Tarball Details ===
npm notice name:          @jupyterlab/github
npm notice version:       2.0.0
npm notice filename:      jupyterlab-github-2.0.0.tgz
npm notice package size:  54.3 kB
npm notice unpacked size: 113.9 kB
npm notice shasum:        ca86cba6c136b9b3b138b1c8f7c50e576630e650
npm notice integrity:     sha512-OeE6CUicyqg1p[...]/FxdT+/s8b/WQ==
npm notice total files:   17
npm notice
jupyterlab-github-2.0.0.tgz

Node v13.13.0

Yarn configuration loaded.
Building jupyterlab assets (build:prod:minimize)
> node /opt/conda/lib/python3.7/site-packages/jupyterlab/staging/yarn.js install --non-interactive
yarn install v1.21.1
[1/5] Validating package.json...
[2/5] Resolving packages...
warning jupyter-leaflet > leaflet.vectorgrid > vector-tile@1.3.0: This module has moved: please install @mapbox/vector-tile instead
warning jupyter-leaflet > leaflet.vectorgrid > vector-tile > point-geometry@0.0.0: This module has moved: please install @mapbox/point-geometry instead
[3/5] Fetching packages...
warning @blueprintjs/core@3.28.0: Invalid bin entry for "upgrade-blueprint-2.0.0-rename" (in "@blueprintjs/core").
warning @blueprintjs/core@3.28.0: Invalid bin entry for "upgrade-blueprint-3.0.0-rename" (in "@blueprintjs/core").
warning sha.js@2.4.11: Invalid bin entry for "sha.js" (in "sha.js").
info fsevents@2.1.3: The platform "linux" is incompatible with this module.
info "fsevents@2.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@1.2.13: The platform "linux" is incompatible with this module.
info "fsevents@1.2.13" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/5] Linking dependencies...
warning "jupyter-leaflet > leaflet.markercluster@1.4.1" has incorrect peer dependency "leaflet@~1.3.1".
[5/5] Building fresh packages...
success Saved lockfile.
Done in 41.26s.

> node /opt/conda/lib/python3.7/site-packages/jupyterlab/staging/yarn.js yarn-deduplicate -s fewer --fail
yarn run v1.21.1
$ /opt/conda/share/jupyter/lab/staging/node_modules/.bin/yarn-deduplicate -s fewer --fail
Done in 0.48s.

> node /opt/conda/lib/python3.7/site-packages/jupyterlab/staging/yarn.js run build:prod:minimize
yarn run v1.21.1
$ ensure-max-old-space webpack --config webpack.prod.minimize.config.js
child_process.js:632
    throw err;
    ^

Error: Command failed: /opt/conda/share/jupyter/lab/staging/node_modules/.bin/webpack --config webpack.prod.minimize.config.js
    at checkExecSyncError (child_process.js:611:11)
    at Object.execFileSync (child_process.js:629:15)
    at Object.<anonymous> (/opt/conda/share/jupyter/lab/staging/node_modules/@jupyterlab/buildutils/lib/ensure-max-old-space.js:38:17)
    at Module._compile (internal/modules/cjs/loader.js:1123:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1143:10)
    at Module.load (internal/modules/cjs/loader.js:972:32)
    at Function.Module._load (internal/modules/cjs/loader.js:872:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47 {
  status: null,
  signal: 'SIGKILL',
  output: [ null, null, null ],
  pid: 176,
  stdout: null,
  stderr: null
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

JupyterLab failed to build
Traceback (most recent call last):

  File "/opt/conda/lib/python3.7/site-packages/jupyterlab/debuglog.py", line 47, in debug_logging
    yield

  File "/opt/conda/lib/python3.7/site-packages/jupyterlab/labextensions.py", line 105, in start
    command=command, app_options=app_options)

  File "/opt/conda/lib/python3.7/site-packages/jupyterlab/commands.py", line 460, in build
    command=command, clean_staging=clean_staging)

  File "/opt/conda/lib/python3.7/site-packages/jupyterlab/commands.py", line 661, in build
    raise RuntimeError(msg)

RuntimeError: JupyterLab failed to build

Exiting application: jupyter
root@5c8558e88e72:~#
```

**Comment by ChristophSchranz** [comment]
This looks unfamiliar, but could be an error that resulted from the latest commit this week. Does it work with a version from last week?

**Comment by dbabbitt** [comment]
Try from this version? https://github.com/iot-salzburg/gpu-jupyter/commit/6a9ff52beadcfffb673e416844dd79927285c0a1

**Comment by ChristophSchranz** [comment]
Sorry for letting you wait so long.
The problem in a `docker-compose ps` is, that the raw `docker-compose.yml` is invalid, if the environment variable for JUPYTER_PORT is not set.
This is the reason, why the call of wrapper scripts `*-local.sh` are suggested. In the commit f22862e5035211bde559792364b0d200d7615c92 I've added a `show-local.sh` that simply sets the env var to a default value and runs a `docker-compose logs -f`. The output is what you have expected!
